LABEL_MAPS = {
    'age_group':            {1:'15–19', 2:'20–24', 3:'25–29', 4:'30–34',
                             5:'35–39', 6:'40–44', 7:'45–49'},
    'residence':            {1:'Urban', 2:'Rural'},
    'region':               {1: 'Adamawa',2: 'Centre (without Yaounde)',3: 'Douala',
                                4: 'East',5: 'Far-North',6: 'Littoral (without Douala)',
                                8: 'North-West',9: 'West',10: 'South',
                                11: 'South-West',12: 'Yaounde'
                            },
    'edu_woman':            {0:'No education', 1:'Primary',
                             2:'Secondary',    3:'Higher'},
    'edu_husband':          {0:'No education', 1:'Primary',
                             2:'Secondary',    3:'Higher' ,8:'Dont Know'},
    'wealth':               {1:'Poorest', 2:'Poorer', 3:'Middle',
                             4:'Richer',  5:'Richest'},
    'religion':             {1: 'Catholic',
                                2: 'Protestant',
                                3: 'Other Christians',
                                4: 'Muslim',
                                5: 'Animist',
                                7: 'None',
                                96: 'Other'},
    'marital_status':       {1:'Formally married', 2:'Cohabiting'},
    'woman_working':        {0:'Not working', 1:'Working'},
    'husband_working':      {0:'Not working', 1:'Working' ,2:'Dont Know'},
    'husband_desired_children': {3:'Wants fewer', 1:'Wants same',
                                2:'Wants more', 8:'Dont Know'},
    'children_group':       {1:' <3 children', 2:'3–5 children',
                             3:'>5 children'},
    'fertility_preference': {1:'Wants More', 2:'Doesn\'t want more/ Undecided',
                             3:'Cannot have children', 4:'Never had sex'},
    'anc_group':            {1:'No ANC', 2:'1–3 visits',
                             3:'>=4 visits', 0:'No pregnancy in last 5 years'},
    'facility_fp':          {0:'No', 1:'Yes',2:'Didn\'t visit facility'},
    'media_any':            {0:'No', 1:'Yes'},
    'current_method':         {0.0: 'Not using',
                                1.0: 'Pill',
                                2.0: 'IUD',
                                3.0: 'Injections',
                                4.0: 'Diaphragm',
                                5.0: 'Male condom',
                                6.0: 'Female sterilization',
                                7.0: 'Male sterilization',
                                8.0: 'Periodic abstinence',
                                9.0: 'Withdrawal',
                                10.0: 'Other traditional',
                                11.0: 'Implants/Norplant',
                                12.0: 'Prolonged abstinence',
                                13.0: 'Lactational amenorrhea (LAM)',
                                14.0: 'Female condom',
                                15.0: 'Foam or jelly',
                                16.0: 'Emergency contraception',
                                17.0: 'Other modern method',
                                18.0: 'Standard days method (SDM)',
                                19.0: 'Specific method 1',
                                20.0: 'Specific method 2'},
    'fieldworker_fp':       {0:'No', 1:'Yes',2:'Didn\'t visit facility'},
}
OUTCOME_LABELS = {
    1: 'Woman alone',
    2: 'Partner alone',
    3: 'Joint decision',
    6: 'Other'
}